In [29]:
import pandas as pd
import sqlite3

In [30]:
conn = sqlite3.connect("olist.db")

In [31]:
!pip install --upgrade prettytable

Requirement already satisfied: prettytable in c:\users\amanda\anaconda3\lib\site-packages (3.18.0)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\amanda\anaconda3\lib\site-packages (from prettytable) (0.8.2)

In [32]:
%config SqlMagic.autopandas = True

In [33]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [34]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [35]:
%sql sqlite:///olist.db

In [36]:
customers = pd.read_csv("olist_customers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

In [37]:
customers.to_sql("olist_customers_dataset", conn, if_exists="replace", index=False)
geolocation.to_sql("olist_geolocation_dataset", conn, if_exists="replace", index=False)
order_items.to_sql("olist_order_items_dataset", conn, if_exists="replace", index=False)
order_payments.to_sql("olist_order_payments_dataset", conn, if_exists="replace", index=False)
order_reviews.to_sql("olist_order_reviews_dataset", conn, if_exists="replace", index=False)
orders.to_sql("olist_orders_dataset", conn, if_exists="replace", index=False)
products.to_sql("olist_products_dataset", conn, if_exists="replace", index=False)
sellers.to_sql("olist_sellers_dataset", conn, if_exists="replace", index=False)
category_translation.to_sql("product_category_name_translation", conn, if_exists="replace", index=False)

71

In [38]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn)

                                name
0            olist_customers_dataset
1          olist_geolocation_dataset
2          olist_order_items_dataset
3       olist_order_payments_dataset
4        olist_order_reviews_dataset
5               olist_orders_dataset
6             olist_products_dataset
7              olist_sellers_dataset
8  product_category_name_translation

In [40]:
%%sql

SELECT *
FROM olist_orders_dataset
LIMIT 10;

 * sqlite:///olist.db
Done.

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,None,None,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [49]:
%%sql

SELECT COUNT(*) AS total_orders
FROM olist_orders_dataset;

 * sqlite:///olist.db
Done.

   total_orders
0         99441

In [42]:
%%sql

SELECT COUNT(DISTINCT customer_id) AS unique_customers
FROM olist_customers_dataset;

 * sqlite:///olist.db
Done.

   unique_customers
0             99441

In [43]:
%%sql

SELECT 
    MIN(order_purchase_timestamp) AS first_order,
    MAX(order_purchase_timestamp) AS last_order
FROM olist_orders_dataset;

 * sqlite:///olist.db
Done.

           first_order           last_order
0  2016-09-04 21:15:19  2018-10-17 17:30:18

In [44]:
%%sql

SELECT 
    order_status,
    COUNT(*) AS order_count
FROM olist_orders_dataset
GROUP BY order_status
ORDER BY order_count DESC;

 * sqlite:///olist.db
Done.

  order_status  order_count
0    delivered        96478
1      shipped         1107
2     canceled          625
3  unavailable          609
4     invoiced          314
5   processing          301
6      created            5
7     approved            2

In [50]:
%%sql

SELECT 
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM olist_order_payments_dataset;

 * sqlite:///olist.db
Done.

   total_revenue
0    16008872.12

In [51]:
%%sql

SELECT 
    payment_type,
    COUNT(*) AS transactions,
    ROUND(SUM(payment_value), 2) AS revenue
FROM olist_order_payments_dataset
GROUP BY payment_type
ORDER BY revenue DESC;

 * sqlite:///olist.db
Done.

  payment_type  transactions      revenue
0  credit_card         76795  12542084.19
1       boleto         19784   2869361.27
2      voucher          5775    379436.87
3   debit_card          1529    217989.79
4  not_defined             3         0.00

In [52]:
%%sql

SELECT 
    ROUND(AVG(order_total), 2) AS average_order_value
FROM (
    SELECT 
        order_id,
        SUM(payment_value) AS order_total
    FROM olist_order_payments_dataset
    GROUP BY order_id
);

 * sqlite:///olist.db
Done.

   average_order_value
0               160.99

In [53]:
%%sql

SELECT
    STRFTIME('%Y-%m', o.order_purchase_timestamp) AS month,
    ROUND(SUM(p.payment_value), 2) AS revenue
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
GROUP BY month
ORDER BY month;

 * sqlite:///olist.db
Done.

      month     revenue
0   2016-09      252.24
1   2016-10    59090.48
2   2016-12       19.62
3   2017-01   138488.04
4   2017-02   291908.01
5   2017-03   449863.60
6   2017-04   417788.03
7   2017-05   592918.82
8   2017-06   511276.38
9   2017-07   592382.92
10  2017-08   674396.32
11  2017-09   727762.45
12  2017-10   779677.88
13  2017-11  1194882.80
14  2017-12   878401.48
15  2018-01  1115004.18
16  2018-02   992463.34
17  2018-03  1159652.12
18  2018-04  1160785.48
19  2018-05  1153982.15
20  2018-06  1023880.50
21  2018-07  1066540.75
22  2018-08  1022425.32
23  2018-09     4439.54
24  2018-10      589.67

In [54]:
%%sql

WITH monthly_revenue AS (
    SELECT
        STRFTIME('%Y-%m', o.order_purchase_timestamp) AS month,
        SUM(p.payment_value) AS revenue
    FROM olist_orders_dataset o
    JOIN olist_order_payments_dataset p
        ON o.order_id = p.order_id
    GROUP BY month
)

SELECT
    month,
    ROUND(revenue, 2) AS revenue,
    ROUND(
        (revenue - LAG(revenue) OVER (ORDER BY month))
        / LAG(revenue) OVER (ORDER BY month) * 100,
        2
    ) AS mom_growth_pct
FROM monthly_revenue
ORDER BY month;

 * sqlite:///olist.db
Done.

      month     revenue  mom_growth_pct
0   2016-09      252.24             NaN
1   2016-10    59090.48        23326.29
2   2016-12       19.62          -99.97
3   2017-01   138488.04       705751.38
4   2017-02   291908.01          110.78
5   2017-03   449863.60           54.11
6   2017-04   417788.03           -7.13
7   2017-05   592918.82           41.92
8   2017-06   511276.38          -13.77
9   2017-07   592382.92           15.86
10  2017-08   674396.32           13.84
11  2017-09   727762.45            7.91
12  2017-10   779677.88            7.13
13  2017-11  1194882.80           53.25
14  2017-12   878401.48          -26.49
15  2018-01  1115004.18           26.94
16  2018-02   992463.34          -10.99
17  2018-03  1159652.12           16.85
18  2018-04  1160785.48            0.10
19  2018-05  1153982.15           -0.59
20  2018-06  1023880.50          -11.27
21  2018-07  1066540.75            4.17
22  2018-08  1022425.32           -4.14
23  2018-09     4439.54          -99.57
24  2018-10      589.67          -86.72

In [55]:
%%sql

SELECT
    p.product_category_name,
    COUNT(DISTINCT oi.order_id) AS orders,
    ROUND(SUM(oi.price), 2) AS product_revenue
FROM olist_order_items_dataset oi
JOIN olist_products_dataset p
    ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY product_revenue DESC
LIMIT 20;

 * sqlite:///olist.db
Done.

     product_category_name  orders  product_revenue
0             beleza_saude    8836       1258681.34
1       relogios_presentes    5624       1205005.68
2          cama_mesa_banho    9417       1036988.68
3            esporte_lazer    7720        988048.97
4   informatica_acessorios    6689        911954.32
5         moveis_decoracao    6449        729762.49
6               cool_stuff    3632        635290.85
7    utilidades_domesticas    5884        632248.66
8               automotivo    3897        592720.11
9       ferramentas_jardim    3518        485256.46
10              brinquedos    3886        483946.60
11                   bebes    2885        411764.89
12              perfumaria    3162        399124.87
13               telefonia    4199        323667.53
14       moveis_escritorio    1273        273960.70
15               papelaria    2311        230943.23
16                     pcs     181        222963.13
17                pet_shop    1710        214315.41
18   instrumentos_musicais     628        191498.88
19         eletroportateis     630        190648.58

In [56]:
%%sql

SELECT
    COALESCE(t.product_category_name_english, p.product_category_name)
        AS category,
    COUNT(DISTINCT oi.order_id) AS orders,
    ROUND(SUM(oi.price), 2) AS revenue
FROM olist_order_items_dataset oi
JOIN olist_products_dataset p
    ON oi.product_id = p.product_id
LEFT JOIN product_category_name_translation t
    ON p.product_category_name = t.product_category_name
GROUP BY category
ORDER BY revenue DESC
LIMIT 20;

 * sqlite:///olist.db
Done.

                 category  orders     revenue
0           health_beauty    8836  1258681.34
1           watches_gifts    5624  1205005.68
2          bed_bath_table    9417  1036988.68
3          sports_leisure    7720   988048.97
4   computers_accessories    6689   911954.32
5         furniture_decor    6449   729762.49
6              cool_stuff    3632   635290.85
7              housewares    5884   632248.66
8                    auto    3897   592720.11
9            garden_tools    3518   485256.46
10                   toys    3886   483946.60
11                   baby    2885   411764.89
12              perfumery    3162   399124.87
13              telephony    4199   323667.53
14       office_furniture    1273   273960.70
15             stationery    2311   230943.23
16              computers     181   222963.13
17               pet_shop    1710   214315.41
18    musical_instruments     628   191498.88
19       small_appliances     630   190648.58

In [57]:
%%sql

SELECT
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS number_of_orders,
    ROUND(SUM(p.payment_value), 2) AS total_spend
FROM olist_customers_dataset c
JOIN olist_orders_dataset o
    ON c.customer_id = o.customer_id
JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spend DESC
LIMIT 20;

 * sqlite:///olist.db
Done.

                  customer_unique_id  number_of_orders  total_spend
0   0a0a92112bd4c708ca5fde585afaa872                 1     13664.08
1   46450c74a0d8c5ca9395da1daac6c120                 3      9553.02
2   da122df9eeddfedc1dc1f5349a1a690c                 2      7571.63
3   763c8b1c9c68a0229c42c9fc6f662b93                 1      7274.88
4   dc4802a71eae9be1dd28f5d788ceb526                 1      6929.31
5   459bef486812aa25204be022145caa62                 1      6922.21
6   ff4159b92c40ebe40454e3e6a7c35ed6                 1      6726.66
7   4007669dec559734d6f53e029e360987                 1      6081.54
8   5d0a2980b292d049061542014e8960bf                 1      4809.44
9   eebb5dda148d3893cdaf5b5ca3040ccb                 1      4764.34
10  48e1ac109decbb87765a3eade6854098                 1      4681.78
11  c8460e4251689ba205045f3ea17884a1                 4      4655.91
12  edde2314c6c30e864a128ac95d6b2112                 1      4513.32
13  a229eba70ec1c2abef51f04987deb7a5                 1      4445.50
14  edf81e1f3070b9dac83ec83dacdbb9bc                 1      4194.76
15  fa562ef24d41361e476e748681810e1e                 1      4175.26
16  ca27f3dac28fb1063faddd424c9d95fa                 1      4163.51
17  055ec572ac7f3c7bdd04a183830ebe59                 2      4053.08
18  5e713be0853d8986528d7869a0811d2b                 1      4042.74
19  58483a1c055dfb600f57c5b867174542                 1      4034.44

In [58]:
%%sql

WITH customer_spend AS (
    SELECT
        c.customer_unique_id,
        SUM(p.payment_value) AS total_spend
    FROM olist_customers_dataset c
    JOIN olist_orders_dataset o
        ON c.customer_id = o.customer_id
    JOIN olist_order_payments_dataset p
        ON o.order_id = p.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    customer_unique_id,
    ROUND(total_spend, 2) AS total_spend,
    CASE
        WHEN total_spend >= 1000 THEN 'High Value'
        WHEN total_spend >= 500 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer_spend
ORDER BY total_spend DESC;

 * sqlite:///olist.db
Done.

                     customer_unique_id  total_spend customer_segment
0      0a0a92112bd4c708ca5fde585afaa872     13664.08       High Value
1      46450c74a0d8c5ca9395da1daac6c120      9553.02       High Value
2      da122df9eeddfedc1dc1f5349a1a690c      7571.63       High Value
3      763c8b1c9c68a0229c42c9fc6f662b93      7274.88       High Value
4      dc4802a71eae9be1dd28f5d788ceb526      6929.31       High Value
...                                 ...          ...              ...
96090  b33336f46234b24a613ad9064d13106d        10.89        Low Value
96091  bd06ce0e06ad77a7f681f1a4960a3cc6        10.07        Low Value
96092  317cfc692e3f86c45c95697c61c853a6         9.59        Low Value
96093  4fa4365000c7090fcb8cad5713c6d3db         0.00        Low Value
96094  968fac81e2c44fb6c1e3ac2a45e6a102         0.00        Low Value

[96095 rows x 3 columns]

In [59]:
%%sql

SELECT
    ROUND(AVG(review_score), 2) AS average_review_score
FROM olist_order_reviews_dataset;

 * sqlite:///olist.db
Done.

   average_review_score
0                  4.09

In [60]:
%%sql

SELECT
    r.review_score,
    COUNT(DISTINCT r.order_id) AS orders,
    ROUND(SUM(p.payment_value), 2) AS revenue
FROM olist_order_reviews_dataset r
JOIN olist_order_payments_dataset p
    ON r.order_id = p.order_id
GROUP BY r.review_score
ORDER BY r.review_score;

 * sqlite:///olist.db
Done.

   review_score  orders     revenue
0             1   11392  2231811.62
1             2    3148   544035.58
2             3    8160  1239884.94
3             4   19098  2960722.31
4             5   57076  8955199.96

In [61]:
%%sql

SELECT
    r.review_score,
    COUNT(*) AS orders,
    ROUND(
        AVG(
            JULIANDAY(o.order_delivered_customer_date)
            - JULIANDAY(o.order_purchase_timestamp)
        ),
        2
    ) AS avg_delivery_days
FROM olist_order_reviews_dataset r
JOIN olist_orders_dataset o
    ON r.order_id = o.order_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY r.review_score
ORDER BY r.review_score;

 * sqlite:///olist.db
Done.

   review_score  orders  avg_delivery_days
0             1    9409              21.31
1             2    2941              16.66
2             3    7962              14.26
3             4   18987              12.31
4             5   57060              10.69

In [62]:
%%sql

SELECT
    oi.seller_id,
    COUNT(DISTINCT oi.order_id) AS orders,
    ROUND(SUM(oi.price), 2) AS revenue,
    ROUND(AVG(r.review_score), 2) AS avg_review_score
FROM olist_order_items_dataset oi
JOIN olist_order_reviews_dataset r
    ON oi.order_id = r.order_id
GROUP BY oi.seller_id
HAVING COUNT(DISTINCT oi.order_id) >= 50
ORDER BY revenue DESC
LIMIT 20;

 * sqlite:///olist.db
Done.

                           seller_id  orders    revenue  avg_review_score
0   4869f7a5dfa277a7dca6462dcf3b52b2    1124  228071.04              4.12
1   53243585a1d6dc2643021fd1853d8905     356  220740.05              4.08
2   4a3ca9315b744ce9f8e9374361493884    1785  200561.42              3.80
3   fa1c13f2614d7b5c4749cbc52fecda94     581  192774.43              4.34
4   7c67e1448b00f6e969d365cea6b010ab     976  188017.85              3.35
5   7e93a43ef30c4f03f38b393420bc753a     335  176201.88              4.21
6   da8622b14eb17ae2831f4ac5b9dab84a    1308  161993.97              4.07
7   7a67c85e85bb2ce8582c35f2203ad736    1151  141130.58              4.23
8   1025f0e2d44d7041d6cf58b6550e0bfa     907  139484.38              3.85
9   955fee9216a65b617aa5c0531780ce60    1277  133948.81              4.05
10  46dc3b2cc0980fb8ec44634e21d2718e     515  126166.26              4.18
11  6560211a19b47992c3666cc44a7e94c0    1838  122484.82              3.91
12  620c87c171fb2a6dd6e8bb4dec959fc6     733  114015.30              4.22
13  7d13fca15225358621be4086e1eb0964     561  113091.19              4.00
14  5dceca129747e92ff8ef7a997dc4f8ca     321  110488.73              3.99
15  1f50f920176fa81dab994f9023523100    1399  107002.21              3.98
16  cc419e0650a3c5ba77189a1882b7556a    1698  106059.06              4.07
17  a1043bafd471dff536d0c462352beb48     715  101454.16              4.19
18  3d871de0142ce09b7081e2b9d1733cb1    1069   93960.80              4.11
19  edb1ef5e36e0c8cd84eb3c9b003e486d     166   79284.55              4.43

In [63]:
%%sql

WITH category_revenue AS (
    SELECT
        COALESCE(t.product_category_name_english, p.product_category_name)
            AS category,
        SUM(oi.price) AS revenue
    FROM olist_order_items_dataset oi
    JOIN olist_products_dataset p
        ON oi.product_id = p.product_id
    LEFT JOIN product_category_name_translation t
        ON p.product_category_name = t.product_category_name
    GROUP BY category
)

SELECT
    category,
    ROUND(revenue, 2) AS revenue,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
FROM category_revenue
ORDER BY revenue_rank;

 * sqlite:///olist.db
Done.

                     category     revenue  revenue_rank
0               health_beauty  1258681.34             1
1               watches_gifts  1205005.68             2
2              bed_bath_table  1036988.68             3
3              sports_leisure   988048.97             4
4       computers_accessories   911954.32             5
..                        ...         ...           ...
69                    flowers     1110.04            70
70             home_comfort_2      760.27            71
71          cds_dvds_musicals      730.00            72
72  fashion_childrens_clothes      569.85            73
73      security_and_services      283.29            74

[74 rows x 3 columns]

In [64]:
%%sql

SELECT
    order_id,
    ROUND(
        JULIANDAY(order_delivered_customer_date)
        - JULIANDAY(order_purchase_timestamp),
        2
    ) AS delivery_days
FROM olist_orders_dataset
WHERE order_delivered_customer_date IS NOT NULL;

 * sqlite:///olist.db
Done.

                               order_id  delivery_days
0      e481f51cbdc54678b7cc49136f2d6af7           8.44
1      53cdb2fc8bc7dce0b6741e2150273451          13.78
2      47770eb9100c2d0c44946d9cf07ec65d           9.39
3      949d5b44dbf5de918fe9c16f97b45f8a          13.21
4      ad21c59c0840e6cb83a9ceb5573f8159           2.87
...                                 ...            ...
96471  9c5dedf39a927c1b2549525ed64a053c           8.22
96472  63943bddc261676b46f01ca7ac2f7bd8          22.19
96473  83c1379a015df1e13d02aae0204711ab          24.86
96474  11c177c8e97725db2631073c19f07b62          17.09
96475  66dea50a8b16d9b4dee7af250b4be1a5           7.67

[96476 rows x 2 columns]

In [65]:
%%sql

SELECT
    ROUND(AVG(
        JULIANDAY(order_delivered_customer_date)
        - JULIANDAY(order_purchase_timestamp)
    ), 2) AS avg_delivery_days,

    ROUND(MIN(
        JULIANDAY(order_delivered_customer_date)
        - JULIANDAY(order_purchase_timestamp)
    ), 2) AS fastest_delivery,

    ROUND(MAX(
        JULIANDAY(order_delivered_customer_date)
        - JULIANDAY(order_purchase_timestamp)
    ), 2) AS slowest_delivery

FROM olist_orders_dataset
WHERE order_delivered_customer_date IS NOT NULL;

 * sqlite:///olist.db
Done.

   avg_delivery_days  fastest_delivery  slowest_delivery
0              12.56              0.53            209.63

Business question	SQL skills demonstrated
How has revenue changed over time?	CTEs, dates, LAG(), window functions
Which product categories drive revenue?	Multiple JOINs, aggregation
Who are our highest-value customers?	CTEs, aggregation, CASE
Does delivery performance affect reviews?	Date calculations, joins, analysis
Which sellers perform best?	HAVING, aggregation, ranking

Olist E-commerce Analysis
│
├── 1. Data cleaning / preparation
│
├── 2. Exploratory SQL
│
├── 3. Revenue analysis
│   ├── Monthly revenue
│   ├── MoM growth
│   └── Average order value
│
├── 4. Customer analysis
│   ├── Customer spend
│   └── Customer segmentation
│
├── 5. Product analysis
│   └── Category performance
│
├── 6. Operations
│   └── Delivery performance
│
├── 7. Customer satisfaction
│   └── Reviews vs delivery time
│
└── 8. Recommendations

Conclusion / Summary
Project Summary

This analysis explored the Olist e-commerce dataset to investigate sales performance, customer behaviour, product performance, seller performance, delivery times, and customer satisfaction.

The analysis found that total revenue across the dataset was [INSERT TOTAL REVENUE], generated from [INSERT NUMBER OF ORDERS] orders between [INSERT START DATE] and [INSERT END DATE]. The average order value was approximately [INSERT AVERAGE ORDER VALUE].

Revenue trends showed that [INSERT MONTH/YEAR] had the highest revenue, reaching approximately [INSERT HIGHEST MONTHLY REVENUE], while [INSERT MONTH/YEAR] recorded the lowest revenue of [INSERT LOWEST MONTHLY REVENUE]. Month-over-month analysis indicated that the largest increase in revenue occurred in [INSERT MONTH], with growth of [INSERT %].

Product analysis showed that [INSERT TOP PRODUCT CATEGORY] was the highest-revenue category, generating approximately [INSERT REVENUE]. This was followed by [INSERT SECOND CATEGORY] and [INSERT THIRD CATEGORY]. These results suggest that a relatively small number of product categories may account for a significant proportion of overall sales.

Customer analysis identified [INSERT NUMBER] unique customers, with the highest-value customer spending approximately [INSERT AMOUNT]. Based on the customer segmentation analysis, [INSERT NUMBER/%] of customers were classified as high-value, [INSERT NUMBER/%] as medium-value, and [INSERT NUMBER/%] as low-value.

The analysis of customer reviews produced an average review score of [INSERT SCORE] out of 5. Delivery performance also appeared to be related to customer satisfaction, with orders receiving a [INSERT HIGH/LOW] review score having an average delivery time of approximately [INSERT NUMBER] days, compared with [INSERT NUMBER] days for [INSERT COMPARISON REVIEW SCORE] reviews.

Seller analysis identified [INSERT SELLER ID/SELLER] as the highest-revenue seller among sellers with at least 50 orders, generating approximately [INSERT REVENUE] in revenue with an average review score of [INSERT SCORE].

Overall, the analysis highlights several areas that could be relevant to an e-commerce business. These include [INSERT KEY INSIGHT 1], [INSERT KEY INSIGHT 2], and [INSERT KEY INSIGHT 3]. Based on these findings, potential business actions could include [INSERT RECOMMENDATION], [INSERT RECOMMENDATION], and [INSERT RECOMMENDATION].

This project demonstrates the use of SQL for data exploration, relational joins, aggregation, filtering, CTEs, conditional logic, date calculations, and window functions. Python and Pandas were also used to support data analysis and presentation of the results.